services:
  bff:
    image: nginx:1.25-alpine
    ports:
      - "8010:80"
    volumes:
      - ./config/bff/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/bff/nginx/page-not-found.html:/var/www/html/page-not-found.html:ro
      - ./config/bff/nginx/includes:/etc/nginx/includes:ro
    depends_on:
      - chess-game

  chess-game:
    image: nginx:1.25-alpine
    expose:
      - 80
    volumes:
      - ./config/chess-game/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/chess-game/nginx/page-not-found.html:/var/www/html/page-not-found.html:ro
      - ./services/chess-game:/usr/share/nginx/html
